config/routes.rb
UrlMower::Application.routes.draw do
  resources :links

  root 'home#index'

  get ':slug' => 'links#show'

  

end

app/models/link.rb
class Link < ActiveRecord::Base
  after_create :generate_slug#, :screenshot_scrape
  mount_uploader :screenshot, ScreenshotUploader

  def display_slug
    if Rails.env.production?
      'http://urlmower.com/' + self.slug
    else
      'http://localhost:3000/' + self.slug
    end
  end
  
  def generate_slug
    self.slug = self.id.to_s(36)
    self.save
  end

  def screenshot_scrape
    ScreenshotWorker.perform_async(self.id)
    ScrapeWorker.perform_async(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]

  def index
    @top_links = Link.order(clicks: :desc).first(12)
    
    render :json => @top_links.to_json(:methods => :display_slug)
  end

  def show
    if params[:slug]
      @link = Link.find_by(slug: params[:slug])
      if redirect_to @link.original_url
        @link.clicks += 1
        @link.save
      end
    else
      @link = Link.find(params[:id])
    end
  end

  def create
    @link = Link.find_or_create_by_original_url(link_params)

    respond_to do |format|
      format.json { render json: @link.to_json(:methods => :display_slug) }
    end
  end

  private
    def set_link
      @link = Link.find_by(slug: params[:slug])
    end

    def link_params
      params.require(:link).permit(:original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/home/index.html.haml
.container-fluid.mower{:"ng-controller" => 'UrlMowerCtrl'}
  .col-xs-12
    .row{style: 'margin-top:10%;'}
      .col-md-6.center
        .header_container.grass_img
          .header
            URLmower
          %form.form-search{name: "urlMowerForm", :"novalidate" => true, :"ng-submit" => 'createUrl()'}
            .input-group
              %input.form-control{:"ng-model" => "link_url", placeholder: "Enter link here to shorten it...", title: "url_link", required: true, type: 'url', name: "link_url"}
              %span.input-group-btn
                %input.btn.btn-success{:type => 'submit', :value => 'Mow it!'}
            .error-container{:"ng-show" => "urlMowerForm.link_url.$invalid && submitted"}
              %small.error_text{:"ng-show" => "urlMowerForm.link_url.$error.required"}
                a URL is required.
              %small.error_text{:"ng-show" => "urlMowerForm.link_url.$error.url"}
                must begin with http://
              
            
              
    .row
      .created_url.url_box{:"ng-if" => "created_url", :class => 'animate'}
        .text-center
          %h2 Your mowed link: 
          %span
            %a{:"ng-href" => "{{created_url}}"} {{created_url}}
    
    / .row
    /   .top_links{:"ng-if" => "top_links.length"}
    /     %h1.page-header.text-center Trending Links
    /     .col-xs-3{:"ng-repeat" => "link in top_links | orderBy: '-clicks'"}
    /       .thumbnail
    /         .text-center
    /           %h4 {{link.title | limitTo:letterLimit}}
    /           %a{:"ng-href" => "{{link.display_slug}}"} {{link.display_slug}}
    /           %h3 {{link.clicks}} clicks
    /           %a{:"ng-href" => "{{link.original_url}}"} {{link.original_url}}
  %footer
    .text-muted.credit{style: "margin: 0.5% 0 0 0.5%;"}
      %small &copy; 2014 Abdul Miah

app/views/layouts/application.html.haml
!!!
%html{:"ng-app" => "baseApp"}
  %head
    %title UrlMower
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/links/_form.html.haml
= form_for @link do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :original_url
    = f.text_field :original_url
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :clicks
    = f.number_field :clicks
  .field
    = f.label :screenshot
    = f.text_field :screenshot
  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Show', @link
\|
= link_to 'Back', links_path

app/views/links/index.html.haml
%h1 Listing links

%table
  %tr
    %th Original url
    %th Slug
    %th Clicks
    %th Screenshot
    %th Title
    %th
    %th
    %th

  - @links.each do |link|
    %tr
      %td= link.original_url
      %td= link.slug
      %td= link.clicks
      %td= link.screenshot
      %td= link.title
      %td= link_to 'Show', link
      %td= link_to 'Edit', edit_link_path(link)
      %td= link_to 'Destroy', link, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Link', new_link_path

app/views/links/new.html.haml
%h1 New link

= render 'form'

= link_to 'Back', links_path

app/views/links/show.html.haml
%p#notice= notice

%p
  %b Original url:
  = @link.original_url
%p
  %b Slug:
  = @link.slug
%p
  %b Clicks:
  = @link.clicks
%p
  %b Screenshot:
  = @link.screenshot
%p
  %b Title:
  = @link.title

= link_to 'Edit', edit_link_path(@link)
\|
= link_to 'Back', links_path